modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="instrumental"
version="1.0.0"
displayName="Instrumental"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pedro, MCreator"

[[dependencies.instrumental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.instrumental]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"

