modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="instrumental"
version="1.0.0"
displayName="Instrumental"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pedro, MCreator"

[[dependencies.instrumental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




